CREATE TABLE users (
  id BIGINT NOT NULL AUTO_INCREMENT UNIQUE, 
  name VARCHAR(100) NOT NULL, 
  email VARCHAR(255) NOT NULL UNIQUE, 
  login VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(20) NOT NULL, 
  cpf CHAR(11) NOT NULL UNIQUE, 
  created_at TIMESTAMP DEFAULT  CURRENT_TIMESTAMP, 
  updated_at TIMESTAMP DEFAULT   CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  primary key (id)
);
